### ISSUE TITLE
Participant in the lobby, but name is not displayed to the moderator (develop branch)

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#268]
Hi,

When the participant joins the meeting before it has started and is waiting in the lobby, the moderator gets the notification that someone is in the lobby upon starting the meeting as expected. However, the moderator does not see the name of the guest waiting in the lobby. 

This is from the weekend develop branch.

![lobby](https://user-images.githubusercontent.com/63865380/80503404-68a3e700-8937-11ea-943b-c7bb62ee9148.png)

**Comment by Astagor** [comment]
Confirmed, the bug is in this line:
[https://github.com/havfo/multiparty-meeting/blob/c23d635803b2f2a0a391b02d32ef150062a4d20e/app/src/RoomClient.js#L875](url)

is
`store.dispatch(
					lobbyPeerActions.setLobbyPeerDisplayName(peer.displayName));`

should be:

`store.dispatch(
					lobbyPeerActions.setLobbyPeerDisplayName(peer.displayName, peer.peerId));`

**Comment by misi** [comment]
Thanks @Astagor! Fixed in develop..

**Comment by cap19** [comment]
Wonderful! Thank you both! Appreciate it.

**Comment by misi** [comment]
I will close this issue now. Just let me know if there is any issue with it.

**Comment by cap19** [comment]
I just downloaded the develop branch and tested but the issue still persist. Can't see the name of the guest waiting in the lobby when they arrive first.

**Comment by Astagor** [comment]
Hmmm, it works for me. Can you give a detailed, step by step scenario when it does not work?

**Comment by havfo** [comment]
@cap19 Are you sure that the user in the lobby actually has a displayName set?

**Comment by cap19** [comment]
It looks like displayName is not getting picked up.  Here are my steps:

1.In Chrome  Incognito mode created room test
2. Entered Your Name as cap19 and clicked Audio Only. (Please note my cursor is still in the Your Name field and I haven't tabbed out or hit Enter yet. I just clicked on Audio Only)
3. Screen says: Ok, you are all set.....
4. In regular Chrome browser tab, I open room test and login through oidc.
5. I see flashing shield notifying me that someone is in the lobby
6. I click on it and see the same screen shot posted above - cap19 (guest name) is not displayed.

**Comment by Astagor** [comment]
I did exactly as you've described it, but it works for me...

**Comment by cap19** [comment]
Hum... maybe I didn't downloaded the updated develop branch correctly or something...

I'll try again.

**Comment by havfo** [comment]
I am unable to reproduce this issue.

**Comment by cap19** [comment]
I retested it on few other computers and it works perfectly fine. The issue is resolved  :)
